site_name: Plotly.py Graphing Library
site_url: https://plotly.com/python
site_description: Plotly's Python graphing library makes interactive, publication-quality graphs.

repo_name: plotly/plotly.py
repo_url: https://github.com/plotly/plotly.py

extra_css:
  - assets/stylesheets/custom.css

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/logo.svg
  palette:
    primary: black
    accent: purple
  features:
  - navigation.top
  - navigation.path

hooks:
  - hooks/script.py

plugins:
- mkdocs-jupyter:
    execute: true
    allow_errors: false

- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [packages/python/plotly]
        options:
          preload_modules:
            - _plotly_utils
            - _plotly_future_
          heading_level: 3
          show_bases: false
          show_symbol_type_heading: true
          docstring_style: numpy
          merge_init_into_class: true

nav:
 - Getting Started: index.md
 - Fundamentals:
    - The Figure Data Structure: figure-structure.md
    - Creating and Updating Figures: creating-and-updating-figures.md
    - Displaying Figures: renderers.md
    - Plotly Express: plotly-express.md
    - Static Image Export: static-image-export.md
    - Theming and Templates: templates.md
    - Changes in Version 6: v6-changes.md
    - Version 4 Migration Guide: v4-migration.md
    - Orca: orca-management.md
    - Configuration: configuration-options.md
    - Setting Graph Size: setting-graph-size.md
    - Formatting Ticks: tick-formatting.md
    - Setting the Font, Title, Legend Entries, and Axis Titles: figure-labels.md
    - Axes: axes.md
    - Legends: legend.md
    - Multiple Axes: multiple-axes.md
    - Subplots: subplots.md
    - Multiple Chart Types: graphing-multiple-chart-types.md
    - Plotly Express Arguments: px-arguments.md
    - Styling Markers: marker-style.md
    - Continuous Colorscales and Colorbars: colorscales.md
    - Text and Annotations: text-and-annotations.md
    - Hover Text and Formatting: hover-text-and-formatting.md
    - Images: images.md
    - Shapes: shapes.md
    - Troubleshooting: troubleshooting.md
    - Built-in Continuous Color Scales: builtin-colorscales.md
    - Discrete Colors: discrete-color.md
    - Styling Plotly Express: styling-plotly-express.md
    - Interactive HTML Export: interactive-html-export.md
    - Pandas Plotting Backend: pandas-backend.md
    - Figure Factories: figure-factories.md
    - Wide Form: wide-form.md
    - Graph Objects: graph-objects.md
    - Figure Introspection: figure-introspection.md
    - Horizontal and Vertical Lines and Rectangles: horizontal-vertical-shapes.md
    - Selections: selections.md
    - Performance: performance.md

 - Basic Charts:
    - Scatter Plots:  line-and-scatter.md
    - Line Charts:  line-charts.md
    - Bar Charts:  bar-charts.md
    - Pie Charts:  pie-charts.md
    - Bubble Charts:  bubble-charts.md
    - Dot Plots:  dot-plots.md
    - Filled Area Plots:  filled-area-plots.md
    - Horizontal Bar Charts:  horizontal-bar-charts.md
    - Gantt Charts:  gantt.md
    - Sunburst Charts:  sunburst-charts.md
    - Tables:  table.md
    - Sankey Diagram:  sankey-diagram.md
    - Treemap Charts:  treemaps.md
    - Figure Factory Tables:  figure-factory-table.md
    - Categorical Axes:  categorical-axes.md
    - Icicle Charts:  icicle-charts.md
    - Patterns, Hatching, Texture:  pattern-hatching-texture.md
    - Dumbbell Plots:  dumbbell-plots.md

 - Statistical Charts:
    - Error Bars: error-bars.md
    - Box Plots: box-plots.md
    - Histograms: histograms.md
    - Distplots: distplot.md
    - 2D Histograms: 2D-Histogram.md
    - Scatterplot Matrix: splom.md
    - Facet and Trellis Plots: facet-plots.md
    - Parallel Categories Diagram: parallel-categories-diagram.md
    - Tree Plots: tree-plots.md
    - Violin Plots: violin.md
    - 2D Histogram Contour: 2d-histogram-contour.md
    - Linear and Non-Linear Trendlines: linear-fits.md
    - Marginal Distribution Plots: marginal-plots.md
    - Strip Charts: strip-charts.md
    - Continuous Error Bands: continuous-error-bars.md
    - Empirical Cumulative Distribution Plots: ecdf-plots.md

 - Scientific Charts:
    - Contour Plots: contour-plots.md
    - Heatmaps: heatmaps.md
    - Imshow: imshow.md
    - Ternary Plots: ternary-plots.md
    - Log Plots: log-plot.md
    - Dendrograms: dendrogram.md
    - Annotated Heatmaps: annotated-heatmap.md
    - Ternary Overlay: ternary-scatter-contour.md
    - Parallel Coordinates Plot: parallel-coordinates-plot.md
    - Quiver Plots: quiver-plots.md
    - Streamline Plots: streamline-plots.md
    - Network Graphs: network-graphs.md
    - Carpet Plots: carpet-plot.md
    - Carpet Contour Plot: carpet-contour.md
    - Carpet Scatter Plot: carpet-scatter.md
    - Polar Charts: polar-chart.md
    - Radar Charts: radar-chart.md
    - Ternary Contours: ternary-contour.md
    - Wind Rose Charts: wind-rose-charts.md
    - Smith Charts: smith-charts.md

 - Financial Charts:
    - Time Series and Date Axes: time-series.md
    - Candlestick Charts: candlestick-charts.md
    - Waterfall Charts: waterfall-charts.md
    - Funnel Charts: funnel-charts.md
    - OHLC Charts: ohlc-charts.md
    - Indicators: indicator.md
    - Gauge Charts: gauge-charts.md
    - Bullet Charts: bullet-charts.md

 - Maps:
    - Maplibre Migration:  migrate-to-maplibre.md
    - Tile Choropleth Maps:  tile-county-choropleth.md
    - Lines on Tile Maps:  lines-on-tile-maps.md
    - Filled Area on Tile Maps:  filled-area-tile-maps.md
    - Bubble Maps:  bubble-maps.md
    - Density Heatmap:  density-heatmaps.md
    - Lines on Maps:  lines-on-maps.md
    - Choropleth Maps:  choropleth-maps.md
    - Tile Map Layers:  tile-map-layers.md
    - Scatter Plots on Tile Maps:  tile-scatter-maps.md
    - County Choropleth:  county-choropleth.md
    - Scatter Plots on Maps:  scatter-plots-on-maps.md
    - Map Configuration and Styling on Geo Maps:  map-configuration.md
    - Hexbin Mapbox:  hexbin-mapbox.md

 - AI and ML:
    - ML Regression: ml-regression.md
    - kNN Classification: ml-knn.md
    - ROC and PR Curves: ml-roc-pr.md
    - PCA Visualization: ml-pca.md
    - AI/ML Apps with Dash: ml-apps.md
    - t-SNE and UMAP projections: ml-tsne-umap-projections.md

 - Visualizing Biological Data:
    - Volcano Plot: volcano.md
    - Manhattan Plot: manhattan.md
    - Clustergram: clustergram.md
    - Alignment Chart: alignment-chart.md

 - 3D Charts:
    - 3D Axes: 3d-axes.md
    - 3D Scatter Plots: 3d-scatter-plots.md
    - 3D Surface Plots: 3d-surface-plots.md
    - 3D Subplots: 3d-subplots.md
    - 3D Camera Controls: 3d-camera-controls.md
    - 3D Bubble Charts: 3d-bubble-charts.md
    - 3D Line Plots: 3d-line-plots.md
    - Trisurf: trisurf.md
    - 3D Mesh Plots: 3d-mesh.md
    - 3D Isosurface Plots: 3d-isosurface-plots.md
    - 3D Volume Plots: 3d-volume.md
    - 3D Cone Plots: cone-plot.md
    - 3D Streamtube Plots: streamtube-plot.md

 - Subplots:
    - Mixed Subplots:  mixed-subplots.md
    - Map Subplots:  map-subplots-and-small-multiples.md
    - Table and Chart Subplots:  table-subplots.md
    - Figure Factory Subplots:  figure-factory-subplots.md

 - Jupyter Widgets:
    - FigureWidget Overview:  figurewidget.md
    - JupyterLab with FigureWidget:  jupyter-lab-tools.md
    - Interactive Data Analysis with FigureWidgets:  figurewidget-app.md
    - Click Events:  click-events.md

 - Custom Controls:
    - Custom Buttons: custom-buttons.md
    - Sliders: sliders.md
    - Dropdowns: dropdowns.md
    - Range Slider: range-slider.md

 - Animations:
    - Intro to Animations: animations.md

 - Advanced:
    - Plot CSV Data: plot-data-from-csv.md
    - Random Walk: random-walk.md
    - Peak Finding: peak-finding.md
    - Smoothing: smoothing.md
    - LaTeX: LaTeX.md

 - API Reference:
    - plotly.express: reference/plotly_express/index.md
    - plotly.graph_objects:
      - Figure: reference/graph_objects/Figure.md
      - Layout: reference/graph_objects/Layout.md
      - Traces:
        - Bar: reference/graph_objects/Bar.md
        - Barpolar: reference/graph_objects/Barpolar.md
        - Box: reference/graph_objects/Box.md
        - Candlestick: reference/graph_objects/Candlestick.md
        - Carpet: reference/graph_objects/Carpet.md
        - Choropleth: reference/graph_objects/Choropleth.md
        - Choroplethmap: reference/graph_objects/Choroplethmap.md
        - Choroplethmapbox: reference/graph_objects/Choroplethmapbox.md
        - Cone: reference/graph_objects/Cone.md
        - Contour: reference/graph_objects/Contour.md
        - Contourcarpet: reference/graph_objects/Contourcarpet.md
        - Densitymap: reference/graph_objects/Densitymap.md
        - Densitymapbox: reference/graph_objects/Densitymapbox.md
        - Funnel: reference/graph_objects/Funnel.md
        - Funnelarea: reference/graph_objects/Funnelarea.md
        - Heatmap: reference/graph_objects/Heatmap.md
        - Histogram: reference/graph_objects/Histogram.md
        - Histogram2d: reference/graph_objects/Histogram2d.md
        - Histogram2dContour: reference/graph_objects/Histogram2dContour.md
        - Icicle: reference/graph_objects/Icicle.md
        - Image: reference/graph_objects/Image.md
        - Indicator: reference/graph_objects/Indicator.md
        - Isosurface: reference/graph_objects/Isosurface.md
        - Mesh3d: reference/graph_objects/Mesh3d.md
        - Ohlc: reference/graph_objects/Ohlc.md
        - Parcats: reference/graph_objects/Parcats.md
        - Parcoords: reference/graph_objects/Parcoords.md
        - Pie: reference/graph_objects/Pie.md
        - Sankey: reference/graph_objects/Sankey.md
        - Scatter: reference/graph_objects/Scatter.md
        - Scatter3d: reference/graph_objects/Scatter3d.md
        - Scattercarpet: reference/graph_objects/Scattercarpet.md
        - Scattergeo: reference/graph_objects/Scattergeo.md
        - Scattergl: reference/graph_objects/Scattergl.md
        - Scattermap: reference/graph_objects/Scattermap.md
        - Scattermapbox: reference/graph_objects/Scattermapbox.md
        - Scatterpolar: reference/graph_objects/Scatterpolar.md
        - Scatterpolargl: reference/graph_objects/Scatterpolargl.md
        - Scatterternary: reference/graph_objects/Scatterternary.md
        - Splom: reference/graph_objects/Splom.md
        - Streamtube: reference/graph_objects/Streamtube.md
        - Sunburst: reference/graph_objects/Sunburst.md
        - Surface: reference/graph_objects/Surface.md
        - Table: reference/graph_objects/Table.md
        - Treemap: reference/graph_objects/Treemap.md
        - Violin: reference/graph_objects/Violin.md
        - Volume: reference/graph_objects/Volume.md
        - Waterfall: reference/graph_objects/Waterfall.md
    - plotly.io: reference/plotly_io.md
    - plotly.data: reference/plotly_data.md
    - plotly.colors: reference/plotly_colors.md
    - plotly.subplots: reference/plotly_subplots.md
    - plotly.figure_factory: reference/plotly_figure_factory.md

 - Community Forum: http://community.plotly.com/